export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODCUT_FROM_CART';
export const REMOVE_PRODUCT_ID = 'REMOVE_PRODUCT_ID';
export const SEARCH_PRODUCT = 'SEARCH_PRODUCT';
export const DISPLAY_FORM = 'DISPLAY_FORM';
export const HIDDEN_FORM = 'HIDDEN_FORM';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const UPDATE_PRODUCT= 'UPDATE_PRODUCT';